Key(INVALID, "Invalid Key")
Key(ESC, "Escape")
Key(F1, "F1")
Key(F2, "F2")
Key(F3, "F3")
Key(F4, "F4")
Key(F5, "F5")
Key(F6, "F6")
Key(F7, "F7")
Key(F8, "F8")
Key(F9, "F9")
Key(F10, "F10")
Key(F11, "F11")
Key(F12, "F12")
Key(GRAVE_ACCENT, "Grave Accent")
Key(0, "0")
Key(1, "1")
Key(2, "2")
Key(3, "3")
Key(4, "4")
Key(5, "5")
Key(6, "6")
Key(7, "7")
Key(8, "8")
Key(9, "9")
Key(MINUS, "Minus")
Key(EQUAL, "Equal")
Key(BACKSPACE, "Backspace")
Key(DELETE, "Delete")
Key(TAB, "Tab")
Key(A, "A")
Key(B, "B")
Key(C, "C")
Key(D, "D")
Key(E, "E")
Key(F, "F")
Key(G, "G")
Key(H, "H")
Key(I, "I")
Key(J, "J")
Key(K, "K")
Key(L, "L")
Key(M, "M")
Key(N, "N")
Key(O, "O")
Key(P, "P")
Key(Q, "Q")
Key(R, "R")
Key(S, "S")
Key(T, "T")
Key(U, "U")
Key(V, "V")
Key(W, "W")
Key(X, "X")
Key(Y, "Y")
Key(Z, "Z")
Key(SPACE, "Space")
Key(ENTER, "Enter")
Key(CTRL, "Ctrl")
Key(SHIFT, "Shift")
Key(ALT, "Alt")
Key(UP, "Up")
Key(LEFT, "Left")
Key(DOWN, "Down")
Key(RIGHT, "Right")
Key(PAGE_UP, "Page Up")
Key(PAGE_DOWN, "Page Down")
Key(HOME, "Home")
Key(END, "End")
Key(FORWARD_SLASH, "Forward Slash")
Key(FULLSTOP, "Fullstop")
Key(COMMA, "COMMA")
Key(QUOTE, "QUOTE")
Key(LBRACKET, "Left Bracket")
Key(RBRACKET, "Left Bracket")
Key(SEMICOLON, "Left Bracket")
Key(COLON, "Left Bracket")